### ISSUE TITLE
block_hit_events: no response received

### ISSUE THREAD

**Issue by wh11e7rue** [waveform80/picraft#18]
```python
from picraft import World
from os import environ

world = World(environ["ADDR"])
world.events.main_loop()
```
this code causes
```python-traceback
Traceback (most recent call last):
  File "minimal.py", line 5, in <module>
    world.events.main_loop()
  File "/usr/local/lib/python3.5/site-packages/picraft/events.py", line 376, in main_loop
    self.process()
  File "/usr/local/lib/python3.5/site-packages/picraft/events.py", line 392, in process
    for event in self.poll():
  File "/usr/local/lib/python3.5/site-packages/picraft/events.py", line 352, in poll
    events = list(player_pos_events(self._track_players)) + list(block_hit_events())
  File "/usr/local/lib/python3.5/site-packages/picraft/events.py", line 347, in block_hit_events
    s = self._connection.transact('events.block.hits()')
  File "/usr/local/lib/python3.5/site-packages/picraft/connection.py", line 298, in transact
    return self._receive(required=True)
  File "/usr/local/lib/python3.5/site-packages/picraft/connection.py", line 250, in _receive
    raise NoResponse('no response received')
picraft.exc.NoResponse: no response received
```
tested with Python 3.5 and [this server](https://github.com/wh11e7rue/raspberryjuice)

**Comment by waveform80** [comment]
Ahh, I suspect I may have to add a FAQ about this as I suspect it may be a common problem. This will almost certainly be down to the default timeout being insufficient for use with a remote server. For the full story read the [critique section](http://picraft.readthedocs.org/en/release-0.5/protocol.html#critique) in the protocol docs, but the short version is something like this:

The Minecraft Pi protocol is rather badly designed; most operations return no positive acknowledgement and the only negative acknowledgement is "Fail" (and even that doesn't appear in certain circumstances). So, after a client sends a command, how is it to know whether it's succeeded? The original mcpi library takes a simple approach: it assumes everything succeeds and carries on. You can take this approach if you like by adding `ignore_errors=True` to the constructor like so:

```python
world = World(environ['ADDR'], ignore_errors=True)
```

However, by default the picraft library takes a different approach: it assumes if nothing has been received after a particular timeout, that the command succeeded. How long is the timeout? Well, that's where things get fuzzy. If you're connecting to a `localhost` server (which I figure is probably the majority use case) the timeout can be quite short (which helps with the performance of the library), so the default in picraft is currently 0.3 seconds. However, that's probably too short for remote connections so you may want to experiment with longer timeouts like so:

```python
world = World(environ['ADDR'], timeout=0.5)
```

For that matter, when dealing with remote connections I may need to think a bit more carefully about the timeouts and make `main_loop()` a little more robust to slow connections (ignore `NoResponse` exceptions unless several occur consecutively?).

Anyway, for now I'd be interested to know if longer timeouts solve the issue for you (they'll probably harm the performance of the library I'm afraid - you may want to try combining `ignore_errors` with it if it's too bad).

**Comment by wh11e7rue** [comment]
Oh, it's really "rather badly designed".
In my case, same exception was raised when `timeout=0.5`.
But `timeout=0.75` works correctly. (Ugh)
I'm going to use `ignore_errors`.
Thanks for the reply.

**Comment by waveform80** [comment]
No prob, thanks for the feedback!

Given that remote connections require such a large timeout, and given that picraft's alternate behaviour has already caused a certain amount of confusion, I'm tempted to make `ignore_errors=True` the default and set the default timeout to something large like `1.0` (which won't hurt the performance of the library as long as `ignore_errors` is active).

That would at least make picraft's behaviour consistent with mcpi and capable of being used remotely and locally with default settings. I'll leave this open as an enhancement ticket for 0.6 to remind me to experiment with this a bit further (note to self: try wifi as well as ethernet, and use a slow server like a Pi1 too)
