### ISSUE TITLE
Allow movement direction to be ascertained in the pi version of the game

### ISSUE THREAD

**Issue by NDevox** [waveform80/picraft#20]
I know that the minecraft API doesn't allow this on pi's, but does on raspberry juice.

However I know direction of movement has been implemented here:

http://www.stuffaboutcode.com/p/adventures-in-minecraft-forum.html?place=msg%2Fadventures-in-minecraft-forum%2Fxj6_42BrBAY%2FrEuwnB5gv98J

I want to try write up an algorithm to find a players direction of movement and move it into this library.

I can't have the direction I'm facing on a pi but I'd settle for movement and know others would as well.

Let me know your opinion on it.

**Comment by waveform80** [comment]
Hmm, I could see a case for this being added to the `BasePlayer.heading` and `BasePlayer.direction` properties, i.e. when `BasePlayer.player_id` is present in `Events.track_players`, the properties return values based on movement (with appropriate caveats sprinkled all over the docs so people realize this is a bit of a hack). And obviously, when it's not present throw an appropriate exception.

Given that when a player is being tracked to produce movement events, we're generating a ton of extra network traffic anyway, the processing overhead would be trivial by comparison so it shouldn't hurt performance anywhere. Yup, I'm convinced!

**Comment by NDevox** [comment]
Bril. I'll try build the functionality in when I have time!
